### ISSUE TITLE
npm install fails in v7.6.0

### ISSUE THREAD

**Issue by mattcreager** [manifoldco/torus-cli#213]
```
2017-03-01T15:44:53.150180+00:00 app[web.1]: Error: Cannot find module './build/Release/kexec.node'
```

**Comment by DLesage25** [comment]
bump. It was complaining that my Python version was higher before

**Comment by ianlivingstone** [comment]
> bump. It was complaining that my Python version was higher before

Interesting, was this installed via `npm`? Was `node-gyp` complaining (which is written in Python) ?

Torus wont work if installed using Node v7 or Node v8 via npm, due to the kexec dependency. We've had a few discussions internally, we're looking for a kexec replacement that lets us replace the running process with another one.

Right now we use a small node script to detect the current operating system and architecture so we can spawn the right Go binary. 

We may also need to use another strategy, such as having the script create a symlink to the right binary on install instead of at runtime, which would solve the problem.

**Comment by ianlivingstone** [comment]
We also need to update the package.json as we now support win32 (https://github.com/manifoldco/torus-cli/blob/master/packaging/npm/package.json.in)

**Comment by ianlivingstone** [comment]
This has been fixed!
