### ISSUE TITLE
Windows 10 node-gyp rebuild failing

### ISSUE THREAD

**Issue by briangruber** [manifoldco/torus-cli#284]
I can't get torus to install on windows 10. I've tried completely uninstall node, tried version `6.11.4 AND 8.7.0`, I've installed the `windows-build-tools`. I keep getting this error. Any ideas??

```
> kexec@3.0.0 install C:\Users\webbr\AppData\Roaming\npm\node_modules\torus-cli\node_modules\kexec
> node-gyp rebuild


C:\Users\webbr\AppData\Roaming\npm\node_modules\torus-cli\node_modules\kexec>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
The system cannot find the path specified.
gyp: Call to 'node -v |grep "v[^0]" > /dev/null && echo "__NODE_GE_V4__" || true' returned exit status 255 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\webbr\AppData\Roaming\npm\node_modules\torus-cli\node_modules\kexec
gyp ERR! node -v v6.11.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "torus-cli" "-g"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! kexec@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kexec@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kexec package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kexec
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kexec
npm ERR! There is likely additional logging output above.
```

**Comment by ianlivingstone** [comment]
I'll dig into this afternoon!

**Comment by ianlivingstone** [comment]
After doing some testing and investigation, the problem is that [kexec](https://npm.im/node-kexec) doesn't support windows (as windows is not posix compliant). We used this module as a substitute for a proper kexec(3) posix alternative as the node `child_process.exec` does not offer an option to re-use the same pid, file descriptors, etc.

One thing to note is that kexec is not maintained anymore - meaning we should consider migrating off the package or finding another substitute in the long term.

A few options I've come up with to work around/solve this problem:

1. Replace kexec with `child_process.exec` from the node standard library -- meaning we'd fork a new process and then pass the file descriptors to it (lots of extra overhead to support npm installation)
2. Leverage an install and uninstall script ala [go-npm](https://npm.im/go-npm) to place the proper binary (windows, linux, darwin) in the proper path as a part of the install and uninstall process. We could just use `go-npm` directly but it currently doesn't support yarn (easy to add).
3. Take an approach similar to babel-cli that optionally supports `kexec` and then falls back to `child_process.exec`: [babel-node.js](https://github.com/babel/babel/blob/01918c68c196b2dd3ab54a20e2598271041fe50a/packages/babel-cli/src/babel-node.js#L75) - this would require some kind of optional installation of kexec to avoid the `node-gyp` failure.

As of writing, I think the second option has the most promise, so I'm going to take a deeper look at what it'd look like to switch entirely off kexec and look at this approach. The one downside is that if a a user has npm hooks disabled then installing torus via npm wouldn't work. I think this is an ok trade-off as there are multiple ways to acquire torus - open to feedback though!

**Comment by ianlivingstone** [comment]
> Leverage an install and uninstall script ala go-npm to place the proper binary (windows, linux, darwin) in the proper path as a part of the install and uninstall process. We could just use go-npm directly but it currently doesn't support yarn (easy to add).

I looked deeply into this, I can only get it reliably working for global installs (e.g. `npm install -g`) as I can't find a reliable way to retrieve the `node_modules/.bin` path to properly setup the pathing to the Go binary. Secondly, it's really flimsy, as it's sort of a hack around the way npm works --  if npm or yarn's behaviour changes this will break.

Finally, the bigger challenge is cross platform support for all of the different file operations required to setup the pathing properly. 

So, I'm thinking we no longer require kexec -- if it's available then we will use it (ala babel-cli) but will fallback to `child_process.exec` in all other circumstances. I'll take a few minutes to investigate forking kexec so that it ignores building on windows -- meaning we'll only fallback to `exec` on windows.
