### ISSUE TITLE
Cannot set values with non-standard characters

### ISSUE THREAD

**Issue by PatDuJour** [manifoldco/torus-cli#297]
```
$ torus set A=":F`b1/.F!nf./e=0({`zO=_N22Wa2sQGU]VEjD;&(9.EG-[9;aAlI9 u1D7f}Dxq"
-bash: !nf./e=0: event not found
```
`!` would stops the operation

After removing `!` from the value, the output is as follow:
```
torus set SECRET_KEY=":F`b1/.Fnf./e=0({`zO=_N22Wa2sQGU]VEjD;&(9.EG-[9;aAlI9 u1D7f}Dxq"
-bash: command substitution: line 1: syntax error near unexpected token `{'
-bash: command substitution: line 1: `b1/.Fnf./e=0({'
Credentials retrieved
Keypairs retrieved
Encrypting key retrieved
Credential encrypted
Completed Operation

Credential SECRET_KEY has been set at /{removed-pwd}/*/*/SECRET_KEY
```
between the two "`", the content was striped.

**Comment by ianlivingstone** [comment]
I've just reproduce this issue, should have a fix out this afternoon!

**Comment by ianlivingstone** [comment]
I believe bash is interpreting the `\``'s which is why your seeing the the command substitution errors. You'll need to escape all of the special characters (e.g.):

```
torus set A=":F\`b1/.F\!nf./e=0({\`zO=_N22Wa2sQGU]VEjD;&(9.EG-[9;aAlI9 u1D7f}Dxq"
```

Which comes out as (using torus view):

```
A=":F`b1/.F\\!nf./e=0({`zO=_N22Wa2sQGU]VEjD;&(9.EG-[9;aAlI9 u1D7f}Dxq"
```

Unfortunately, there isn't anything we can through the CLI to get around the special character escaping as the string is interpreted by your shell before it's sent to the CLI.

**Comment by PatDuJour** [comment]
@ianlivingstone Thanks for the response. That makes sense.

We have found a workaround, after the import is fixed in [issues/296](https://github.com/manifoldco/torus-cli/issues/296).

**Comment by ianlivingstone** [comment]
@PatDuJour awesome! Happy to hear that :)
